In [1]:
import altair as alt
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
df = pd.read_excel('table5 (1).xlsx')                            #You can also access it directly from github
df.head()   #Will return first 5 rows of the dataset
df

       Land cover types Level       Value
0   NWI marine wetlands   Low    90367611
1            Salt marsh   Low     5836741
2    Freshwater wetland   Low     7416748
3            City parks   Low   249158682
4                 Beach   Low     1748766
5            Freshwater   Low     5632155
6            Oyster bed   Low      609367
7               Estuary   Low     1775730
8            Tidal flat   Low      154979
9                Forest   Low   232570496
10   Grassland/Openland   Low     5588362
11        Core habitats   Low     2566369
12       Coastal waters   Low   101783372
13                Total   Low   705209378
14  NWI marine wetlands  High   596715671
15           Salt marsh  High    38541188
16   Freshwater wetland  High    12222223
17           City parks  High   498317363
18                Beach  High     7527883
19           Freshwater  High    36077699
20           Oyster bed  High     5499626
21              Estuary  High     3826203
22           Tidal flat  High      258298
23               Forest  High   748950958
24   Grassland/Openland  High     9447291
25        Core habitats  High    12831846
26       Coastal waters  High   157984654
27                Total  High  2128200903

In [4]:
# Create the chart
chart = alt.Chart(df).mark_bar().encode(
    x='Land cover types',
    y='Value',
    color='Level'
).properties(
    title='Land cover types by Value of Ecosystem Services',
    width=600,
    height=400
)

chart

alt.Chart(...)